capstone-rust/capstone-rs

- examples/demo.rs
- src/capstone.rs
- src/constants.rs
- src/ffi.rs
- src/instruction.rs
- src/lib.rs
This pull request adds cs_reg_name and cs_insn_name. 
I also reformatted the code with `cargo fmt` (it uses rustfmt), if you don't like the new formatting I can make a PR without it.
> Add bindings for cs_reg_name and cs_insn_name

- Cargo.toml
- THIRD_PARTY.txt
- src/capstone.rs
- src/constants.rs
- src/ffi.rs
- src/instruction.rs
- src/lib.rs
This is a first take at resolving #7. I did not break the interface but expose some of the functionality in the cs_detail.
I did not add any functionality that requires architecture-specific header information (such as instruction or register ids) because the architecture-specific headers are so large and need to be automatically parsed first.
> Expose some of the cs_detail interface

- CHANGELOG.md
- README.md
- examples/demo.rs
- examples/objdump.rs
- src/arch.rs
- src/capstone.rs
- src/constants.rs
- src/error.rs
- src/instruction.rs
- src/lib.rs
Refactors the API, including:
* Partition `Mode` enum into:
- `Mode`: referred to as "basic_mode" by [Capstone documentation](http://www.capstone-engine.org/lang_c.html)
- Example: `Arm`/`Thumb`, `32`/`64`.
- `ExtraMode`: "Extra Mode" in Capstone documentation
- Example: Arm `V8`, Sparc `V9`
- `Endian`: `big`/`little`
* Separate `new()` and `new_raw()` for `Capstone`
- `new()` uses the builder pattern to ensure that only valid values are passed for mode, endian, extra_mode, etc.
- `Capstone::new().x86().mode(x86::ArchMode::Mode64).syntax(x86::ArchSyntax::Intel).build()`
- `Capstone::new().ppc().mode(ppc::ArchMode::Mode32).endian(Endian::Big).build()`
- `new_raw()` has an API similar the original `new()`
- `Capstone::new_raw(Arch::X86, Mode::Mode64, NO_EXTRA_MODE, None)`
- …
> API refactor WIP

- src/capstone.rs
- src/instruction.rs
- src/lib.rs
Also makes `Instructions::from_raw_parts()` private (crate visibility).
Addresses #21
> Return empty instructions instead of an error

- .gitignore
- CHANGELOG.md
- Cargo.toml
- README.md
- scripts/build_readme.sh
- scripts/github-md.css
- src/capstone.rs
- src/constants.rs
- src/error.rs
- src/lib.rs
* Update capstone-sys to 0.7.0
- Brings in Windows support (with `cc` crate)
- Makes enum types more sane
- Add `build_capstone_cc` pass-through feature
* Add script to build readme/changelog
* Update changelog
> Upgrade capstone-sys to 0.7.0

- examples/cstool.rs
IMHO, `stdin` may not need to be mutable and the second `stdin` can be replaced by the value expression `stdin.lock()`.
> simplify stdin.lock()

- README.md
- src/lib.rs
Allocators are enabled on stable in Rust 1.28 and later, so this
now works there.
> Allow alloc_system on current Rust.

- examples/objdump.rs
- src/arch/mod.rs
- src/capstone.rs
- src/test.rs
Discussed in the following post:
https://www.reddit.com/r/rust/comments/9hwr5r/a_rust_ffi_adventure_in_unsafety/
Conclusion:
* There is no need to introduce lifetime for `Capstone` to ensure `Instructions`'s lifetime constrainted.
* The `disasm` methods might not actually need `self` to be mutable, as it only access immutable methods.
* The `disasm` methods uses unbound lifetime, which is not desired here. Bound to `self` instead. However, as the semantic is eager evaluation, there is no need to also bound the code slice.
* Tests fixed to represent that `disasm` is no longer mutating `Capstone`.
This change compiles all tests, but I didn't run the tests, please confirm with your own test before merge.
> Remove lifetime of Capstone, and adjust self mutablity for disasm

- .travis.yml
- CHANGELOG.md
- README.md
- capstone-rs/Cargo.toml
- capstone-rs/ci/test.sh
- capstone-rs/src/arch/arm.rs
- capstone-rs/src/arch/arm64.rs
- capstone-rs/src/arch/evm.rs
- capstone-rs/src/arch/m680x.rs
- capstone-rs/src/arch/m68k.rs
- capstone-rs/src/arch/mips.rs
- capstone-rs/src/arch/mod.rs
- capstone-rs/src/arch/ppc.rs
- capstone-rs/src/arch/sparc.rs
- capstone-rs/src/arch/sysz.rs
- capstone-rs/src/arch/tms320c64x.rs
- capstone-rs/src/arch/x86.rs
- capstone-rs/src/arch/xcore.rs
- capstone-rs/src/capstone.rs
- capstone-rs/src/ffi.rs
- capstone-rs/src/instruction.rs
- capstone-rs/src/lib.rs
- capstone-rs/src/test.rs
- capstone-sys/Cargo.toml
- cstool/Cargo.toml
- cstool/LICENSE
- cstool/README.md
- cstool/src/bin/cstool.rs
- scripts/build_readme.sh
- `clang-8` (available at https://apt.llvm.org/)
- WASI sysroot from https://github.com/CraneStation/wasi-libc
- `wasm-wasi` target for nightly rust toolchain:
~~~
rustup target add --toolchain nightly wasm32-wasi
~~~
- wasmer (to run WASI executable): https://wasmer.io/
Tell `cc` crate to use our WASI sysroot and clang-8 compiler:
~~~sh
cd cstool  # go to path with cstool dir
CFLAGS_wasm32_wasi="--sysroot=/path/to/wasi/sysroot" \
CC=clang-8 \
cargo +nightly build --target=wasm32-wasi
~~~
~~~
cd cstool  # go to path with cstool dir
wasmer run ../target/wasm32-wasi/debug/cstool.wasm -- --arch x86 --mode mode32 --code 909090e812345678
~~~
> Support wasm32-wasi

- .travis.yml
Also, explicitly delete cargo registry src/ directory to save space in
cache.
Recommended by:
https://travis-ci.community/t/stable-rust-channel-outdated/4213/3
> ci: update rust toolchain before script

- capstone-rs/src/arch/x86.rs
- capstone-rs/src/instruction.rs
- capstone-rs/src/test.rs
- capstone-sys/build.rs
- capstone-sys/pre_generated/capstone.rs
I don't think that generating `cs_ac_type` as an enum is a good option — it's a bitflag in fact. I had to write a ton of if-else as a workaround. Suggestions are appreciated!
> capstone: add support for cs_ac_type in x86

- .cirrus.yml
Pkg install was failing:
~~~
pkg install -y bash
Updating FreeBSD repository catalogue...
Fetching meta.txz: . done
pkg: repository meta /var/db/pkg/FreeBSD.meta has wrong version 2
repository FreeBSD has no meta file, using default settings
Fetching packagesite.txz: .......... done
pkg: repository meta /var/db/pkg/FreeBSD.meta has wrong version 2
pkg: Repository FreeBSD load error: meta cannot be loaded No error: 0
Unable to open created repository FreeBSD
Unable to update repository FreeBSD
Error updating repositories!
Exit status: 3
~~~
Example Cirrus CI failure: https://cirrus-ci.com/task/5812812263981056
FreeBSD Bugzilla Bug 244549:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=244549
> Fix failing Cirrus CI FreeBSD tests

- .travis.yml
- capstone-rs/ci/test.sh
Travis CI has changed how these are parsed, so now the exclude section
overrides the include, thus causing no Travis CI jobs to run.
> travis-ci: remove exclude section

- capstone-rs/src/instruction.rs
- capstone-rs/src/test.rs
This PR adds a try_from implementation which allows one to convert from a raw `* const cs_insn` to an `Insn`.
We need this for @frida-rust, as frida generates `cs_insn`s internally, and we'd like to be able to use capstone-rs's rich API on those instructions.
> Add a try_from implementation to convert from a cs_insn to an Insn

- .cirrus.yml
Fixes issue seen for FreeBSD tests:
```
ld-elf.so.1: Undefined symbol "rl_filename_rewrite_hook" referenced from COPY relocation in /usr/local/bin/bash
```
> cirrus-ci: upgrade FreeBSD image to 12.2

- capstone-sys/Cargo.toml
- capstone-sys/build.rs
Bumped the bindgen version used (as packages with newer bindgen were conflicting).
Added WASM support, as without it I was running into issues with missing WASM related symbols.
> Bump bindgen version and add wasm support

- capstone-rs/src/arch/mod.rs
Noticed while profiling that vector resizing was pretty hot when disassembly and getting operands, and it appears to be due to operand iterators not implementing `size_hint`. We can simply delegate size_hint to the underlying iterator.
> arch: Implement size_hint for operand iterators

- capstone-rs/examples/demo.rs
- capstone-rs/src/arch/m68k.rs
- capstone-rs/src/instruction.rs
- capstone-rs/src/lib.rs
- capstone-rs/src/test.rs
- cstool/src/bin/cstool.rs
Removed `Instructions::iter()` and `InstructionIterator`. The nice thing about having a deref to a slice is that it gives you an `iter()` method for free because of Rust's deref coercion. Also fixed some tests so that they use references to `Insn` instead and made `Insn` cloneable as well in case someone did want an `Iterator<Item = Insn>` instead of an `Iterator<Item = &Insn>`.
> Cleanup instruction iterator

- .github/workflows/ci.yml
Only run cargo fmt/clippy on stable toolchain. Also adds useful names to some tests.
> Refine Github Workflow

- capstone-rs/src/instruction.rs
Fixes #121.
EDIT: superseded by #123 !
The `Instructions<'capstone>` owned a heap-allocated `[Insn<'capstone>]` (imagine a `CsBox<[Insn<'capstone>]>`), which thus involves owning the backing storage for the `Insn`s themselves, as well as freeing whatever each `Insn<'capstone>` owns.
- **What does a `Insn<'capstone>` own?** It turns out that as written, currently, it technically doesn't own anything, even if, semantically, it's owning kind of a `Option<CsBox<cs_detail>>`. That is, when its `detail` field is a non-`NULL` pointer, when the `CsBox<[Insns<'capstone>]>` is dropped, such non-`NULL` pointers are `cs_free`d as well.
**So a `Insn<'capstone>`, conceptually, owns a `Box`-like-ish field. Mainly, a non-`Copy` field!**
- and yet `Insn<'capstone>` implements `Clone`, by deriving it from …
> Remove incorrect implementation of `Clone` for `Insn<'capstone>`

- capstone-rs/src/ffi.rs
- capstone-rs/src/instruction.rs
This PR mostly just inlines property accesses, which gave performance improvements of up to 4-6x in my own project.
I also switched to using `from_utf8_unchecked` as the function requires valid UTF8 to be passed anyway. This gave some small performance improvements.
> Some performance changes

- capstone-rs/Cargo.toml
- capstone-rs/examples/demo.rs
- capstone-rs/src/arch/m68k.rs
- capstone-rs/src/capstone.rs
- capstone-rs/src/ffi.rs
- capstone-rs/src/instruction.rs
- capstone-rs/src/test.rs
- capstone-sys/Cargo.toml
- capstone-sys/build.rs
- cstool/Cargo.toml
This PR adds a new default feature, `not_diet` to both crates. If *disabled*, Capstone will be compiled in Diet mode, which would result in speed/size improvements. Currently, many tests will fail if run with this feature disabled, and will need to be gated behind it.
It might be more legible to invert this feature `#[cfg(feature = "diet")]` but I believe Cargo's dependency resolution [requires](https://www.reddit.com/r/rust/comments/sgegah/cargo_features_have_to_be_additive/) that features always _add_ new items, rather than removing them.
Rather than directly returning `None`, we could instead defer to Capstone's API (returning NULL pointers or empty strings) - this way is more explicit but with more repeated code.
> Add not_diet feature

- .github/workflows/main.yml
- CHANGELOG.md
- README.md
- capstone-rs/Cargo.toml
- capstone-rs/ci/test.sh
- capstone-rs/src/arch/mod.rs
- capstone-rs/src/capstone.rs
- capstone-rs/src/error.rs
- capstone-rs/src/ffi.rs
- capstone-rs/src/instruction.rs
- capstone-rs/src/lib.rs
- capstone-sys/build.rs
- cstool/src/bin/cstool.rs
Fixes #141 
Introduces a breaking change with the `std` feature
> Implement Error trait

- capstone-rs/src/capstone.rs
The enum `capstone::Arch` doesn't have the same values as capstone's `cs_arch` enum. This causes calls to `supports_arch()` to return incorrect results once the enum values diverge, which happens for riscv and a few others.
Fortunately, `capstone_sys::cs_arch` has a `From<capstone::Arch>` implementation, so we can just use that to do the correct conversion.
> Fix cs_support enum bug

- capstone-rs/src/arch/mod.rs
- capstone-rs/src/arch/sysz.rs
- capstone-rs/src/instruction.rs
- capstone-rs/src/test.rs
This PR implements `InsnDetail`, `SysZOperand`, etc.  to enable instruction details for sysz. I used the RISC-V implementation as a template, so the code style should follow the rest of the library's conventions.
> Implement InsnDetail (+ associated types) for sysz

- capstone-rs/src/arch/arm.rs
- capstone-rs/src/test.rs
fixes capstone-rust/capstone-rs#97
I've copied the approach from x86 to arm as you've suggested and adjusted the tests accordingly.
> Make RegAccessType available for arm.

- capstone-rs/src/arch/arm.rs
- capstone-rs/src/arch/arm64.rs
- capstone-rs/src/arch/bpf.rs
- capstone-rs/src/arch/evm.rs
- capstone-rs/src/arch/m680x.rs
- capstone-rs/src/arch/m68k.rs
- capstone-rs/src/arch/mips.rs
- capstone-rs/src/arch/mod.rs
- capstone-rs/src/arch/ppc.rs
- capstone-rs/src/arch/riscv.rs
- capstone-rs/src/arch/sparc.rs
- capstone-rs/src/arch/sysz.rs
- capstone-rs/src/arch/tms320c64x.rs
- capstone-rs/src/arch/x86.rs
- capstone-rs/src/arch/xcore.rs
- capstone-rs/src/constants.rs
- capstone-rs/src/instruction.rs
- capstone-rs/src/test.rs
- capstone-sys/build.rs
- capstone-sys/common.rs
- capstone-sys/pre_generated/capstone.rs
capstone-rs crashes on s390x (also knows as SystemZ in the LLVM world)
as follows:
Thread 2 received signal SIGSEGV, Segmentation fault.
0x000002aa00a6a604 in cs_option (ud=140702726002672, type=CS_OPT_SYNTAX, value=2) at capstone/cs.c:782
782             return arch_configs[handle->arch].arch_option(handle, type, value);
(gdb) p/x handle->arch
$7 = 0x7ffb
handle->arch is clearly corrupted. It is assigned as follows in
cs_open():
0x000002aa00a6a44a <+146>:   lgr     %r9,%r3
[...]
0x000002aa00a6a468 <+176>:   rosbg   %r9,%r10,0,31,32
[...]
458                     ud->arch = arch;
459                     ud->mode = mode;
0x000002aa00a6a47a <+194>:   stg     %r9,0(%r13)
Here the 32-bit arch value and the 32-bit mode value are placed into a
64-bit register and stored with one instruction.
The …
> Fix segfault in cs_option() on s390x

- capstone-rs/src/capstone.rs
I think the if cfg! is kinda weird and should probably rather have it just gate the entire function instead? Anyway, I'm not sure how to handle `assert!(len <= ints.len());` better, but it should never happen anyway so it probably doesn't matter?
Also I just picked 64 because python uses that, though I have a hard time imagining reading/writing to more than 64 registers: https://github.com/capstone-engine/capstone/blob/5fb8a423d4455cade99b12912142fd3a0c10d957/bindings/python/capstone/__init__.py#L929
> Regs access

- capstone-rs/src/lib.rs
The `cfg` config for `std`/`ALLOCATOR` might be accidentally too permissive.
Specifically, as it currently stands:
```rs
#[cfg(any(test, not(feature = "std")))]
#[macro_use]
extern crate std;
```
This code brings in `std` even if the feature `std` is not enabled (because `any` would hold true if even one of the two conditions is true). Similarly, for `ALLOCATOR`.
By changing it to `all` instead of `any`, it is only applicable for tests for non-`std` configuration, which is what I believe the intention is here.
> Fix accidentally forced std/allocator on no_std

- capstone-sys/build.rs
When building with Bazel's sandbox, all the capstone source files are actually symlinks. In this case `build.rs` doesn't find any files to build and attempts to link the static library right away.
Reproducer and the error messages can be found [here](https://github.com/bazelbuild/rules_rust/issues/3435).
I tested the change locally on macOS with the following spec:
```bazel
crate.spec(
package = "capstone-sys",
git = "https://github.com/AlexDenisov/capstone-rs.git",
branch = "bazel-compatibility",
)
```
which is working as expected.
Is there anything else I'd need to check to ensure this change doesn't break anything?
> Make `build.rs` compatible with Bazel's sandbox

- .github/workflows/main.yml
- capstone-rs/Cargo.toml
- capstone-sys/Cargo.toml
- capstone-sys/build.rs
I am looking into ways for how we can speed up check-builds in Miri (see https://github.com/rust-lang/miri/issues/4461). The libffi build script accounts for a significant fraction of the remaining build time here since the C code still gets built, even when that is entirely unnecessary for a check build.
In the rustc workspace, we have a `check_only` feature on some crates for exactly this purpose. I wonder if you'd be open to the idea of having a similar feature for libffi? Of course I would prefer to actually have native support in cargo for this but that idea has a bunch of unanswered design questions (https://github.com/rust-lang/cargo/issues/4001). So meanwhile, the best we can do is hack it in ourselves. This is done with a cargo feature to have cargo properly cache the build with …
> add check_only feature to disable building the C code

- capstone-rs/Cargo.toml
When I visit the website in the description of the crate, I see an error page.
Update the description website to accurately capture the www subdomain.
> Update description website in Cargo.toml
