examples/demo.rs
src/capstone.rs
src/constants.rs
src/ffi.rs
src/lib.rs

Better error handling

---

.travis.yml
Cargo.toml

Update `capstone-sys` version.

Update capstone-sys version, authors

---

README.md

`demo.rs` on `README.md` is very old and cannot be compiled even in version `v0.1.0`.
I updated the demo.rs which uses builder pattern.

Update demo.rs on README.md

---

CHANGELOG.md
Cargo.toml
README.md
examples/demo.rs
src/capstone.rs
src/instruction.rs
src/lib.rs

These are mostly minor changes.
Once this pull request goes through, I would like to do a release.

Api improve

---

Cargo.toml
README.md

Also link to GitHub issues.
Handles #24 and #25

Add badges/keywords/doc to README/manifest

---

CHANGELOG.md
Cargo.toml
README.md
examples/demo.rs
examples/objdump.rs
scripts/gen_arch_enums.sh
src/arch/arm.rs
src/arch/arm64.rs
src/arch/mips.rs
src/arch/mod.rs
src/arch/ppc.rs
src/arch/sparc.rs
src/arch/sysz.rs
src/arch/x86.rs
src/arch/xcore.rs
src/capstone.rs
src/instruction.rs
src/lib.rs

* Use enums and traits for different architectures
* Adds unit tests for each architecture
* Adds newtype wrapper for RegId, InsnIdInt, InsnGroupId

Add detail api

---

.travis.yml
appveyor.yml
ci/test.sh

- Run CI tests in debug and release mode.
- Add Appveyor Windows tests

Improve CI tests

---

README.md
ci/test.sh
examples/cstool.rs

Test examples and README code in CI

---

.travis.yml
CHANGELOG.md
README.md
examples/cstool.rs
src/arch/arm.rs

Arm opmem index

---

.cirrus.yml
README.md
capstone-rs/ci/test.sh

Add Cirrus CI support

---

capstone-rs/src/capstone.rs
capstone-rs/src/test.rs

Added explicit skipdata test for *_INS_INVALID

Added set_skipdata() (CS_OPT_SKIPDATA) api

---

appveyor.yml

Attempts to fix #66 
Based on https://github.com/rust-lang/rust/blob/133431470986b91f88a4f90cbe833b64832048a6/appveyor.yml

Use mingw 6.3.0

---

capstone-rs/Cargo.toml
capstone-rs/ci/test.sh
capstone-rs/examples/parallel.rs

Add parallel disassemby example

---

capstone-rs/src/arch/mod.rs

This small change doesn't affect anything but fixes completion in CLion with intellij-rust ([issue](https://github.com/intellij-rust/intellij-rust/issues/6274)).

Fix completion in CLion.

---

README.md
capstone-rs/ci/test.sh
capstone-rs/src/arch/m68k.rs
capstone-rs/src/arch/mod.rs
capstone-rs/src/capstone.rs
capstone-rs/src/error.rs
capstone-rs/src/instruction.rs
capstone-rs/src/lib.rs
capstone-rs/src/test.rs
capstone-sys/build.rs
capstone-sys/common.rs
cstool/src/bin/cstool.rs
scripts/update_readme_code_sample.sh

Cirrus CI Fix

---

.github/workflows/main.yml
.github/workflows/stable-only.yml
capstone-rs/ci/test.sh

Splits Github workflow into separate test and stable-only jobs.

CI: Fix Github Worflow

---

.github/workflows/main.yml
.github/workflows/stable-only.yml
README.md
capstone-rs/examples/demo.rs
capstone-rs/src/instruction.rs
capstone-rs/src/lib.rs
capstone-rs/src/test.rs
cstool/src/bin/cstool.rs

Eliminates need for iterators. Handles issue  #103.

Access Insn group_ids via slice

---

README.md
capstone-rs/src/capstone.rs
capstone-rs/src/instruction.rs
capstone-rs/src/lib.rs

Also remove unneeded Instructions methods.

doc: add links to relevant types/functions

---

.github/workflows/stable-only.yml
capstone-rs/ci/test.sh
capstone-rs/examples/demo.rs
capstone-rs/src/arch/arm.rs
capstone-rs/src/arch/m68k.rs
capstone-rs/src/arch/x86.rs
capstone-rs/src/ffi.rs
capstone-rs/src/test.rs
capstone-sys/build.rs

Valgrind in Ubuntu repo shows false-positive against Rust std library.

ci: install valgrind from snap

---

appveyor.yml

ci: update windows appveyor toolchain

---

capstone-sys/build.rs

add files sort for building-reproducible

---

CHANGELOG.md
capstone-rs/src/capstone.rs
capstone-rs/src/test.rs

Partially implements issue #64

rs: expose CS_OPT_UNSIGNED option via Capstone::set_unsigned

---

capstone-rs/benches/my_benchmark.rs
capstone-rs/src/capstone.rs
capstone-rs/src/test.rs

See discussions in https://github.com/capstone-rust/capstone-rs/pull/115#issuecomment-3115457423.

rs: use lending iterator patten to ensure safety of DisasmIter
